-- DB BigBrother
-- Creé le 08/11/2024
-- Version 1.0
-- Autres Tables de Définition
-- tablesdefinition.sql


-- DEFINITION AUTRES TABLES PERSONNE 

CREATE TABLE IF NOT EXISTS NOM__REF(
    id SERIAL PRIMARY KEY,
    nom VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS PRENOM__REF(
    id SERIAL PRIMARY KEY,
    prenom VARCHAR(50) UNIQUE NOT NULL
);

-- DEFINITION ADRESSE

CREATE TABLE IF NOT EXISTS PAYS__REF(
    id SERIAL PRIMARY KEY,
    nom VARCHAR(50) UNIQUE NOT NULL,
    code VARCHAR(2) UNIQUE NOT NULL,
    indicatif INTEGER UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS VILLE__REF(
    id SERIAL PRIMARY KEY,
    nom VARCHAR(50) NOT NULL,
    id_pays INTEGER NOT NULL,
    CONSTRAINT fk_id_pays_ville FOREIGN KEY (id_pays) REFERENCES PAYS__REF(id)
);

CREATE TABLE IF NOT EXISTS RUE__REF(
    id SERIAL PRIMARY KEY,
    nom VARCHAR(50) NOT NULL,
    id_ville INTEGER NOT NULL,
    id_pays INTEGER NOT NULL,
    CONSTRAINT fk_id_pays_rue FOREIGN KEY (id_pays) REFERENCES PAYS__REF(id),
    CONSTRAINT fk_id_ville_rue FOREIGN KEY (id_ville) REFERENCES VILLE__REF(id)
);

CREATE TABLE IF NOT EXISTS ADRESSE__REF(
    id SERIAL PRIMARY KEY,
    numero INTEGER NOT NULL,
    id_rue INTEGER NOT NULL,
    id_ville INTEGER NOT NULL,
    id_pays INTEGER NOT NULL,
    CONSTRAINT fk_id_rue_adresse FOREIGN KEY (id_rue) REFERENCES RUE__REF(id),
    CONSTRAINT fk_id_pays_adresse FOREIGN KEY (id_pays) REFERENCES PAYS__REF(id),
    CONSTRAINT fk_id_ville_adresse FOREIGN KEY (id_ville) REFERENCES VILLE__REF(id)
);

-- DEFINITION GENRE

CREATE TABLE IF NOT EXISTS GENRE__REF(
    id SERIAL PRIMARY KEY,
    genre VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS RESEAUX__REF(
    id SERIAL PRIMARY KEY,
    reseaux VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS MATRIMONIALE__REF(
    id SERIAL PRIMARY KEY,
    matrimoniale VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS TYPE_RELATION__REF(
    id SERIAL PRIMARY KEY,
    type_relation VARCHAR(20) UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS ADRESSE_MAIL__REF(
    id SERIAL PRIMARY KEY,
    adresse_mail VARCHAR(20) UNIQUE NOT NULL
);